baseURL = "https://digidingo.be/"
languageCode = "nl-be"
title = "DigiDINGO"
theme = "digidingo"

SectionPagesMenu = "main"

[params]
  favicon = ""

[social]
  facebook = "https://facebook.com/"
  twitter = "https://twitter.com/"
  instagram = ""
  linkedin = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true